<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_iPhone</name>
   <tag></tag>
   <elementGuidId>c6e009a1-fae6-4eef-a2c7-a06d9feb8818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;iPhone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'iPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;iPhone&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35c19c60-ac52-45f5-bd17-7dd6ed15f956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost:8080/image/cache/catalog/demo/iphone_1-200x200.jpg</value>
      <webElementGuid>40543224-bfbc-4b91-a89e-4c1c334e64f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>iPhone</value>
      <webElementGuid>31f10ff1-3bfc-4718-bf7e-36429567c2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>iPhone</value>
      <webElementGuid>132e28ca-c93a-421b-9fa3-f418df74d088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>ee3536f1-4ab2-4719-a820-11ad252669ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a055ca626d6a8902e4832820e9f3031b</value>
      <webElementGuid>464138c2-099a-4a0f-b02c-fb138bef2d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'iPhone']</value>
      <webElementGuid>3e6548fb-7440-4e9b-a0d5-e45cbd26c86e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'iPhone']</value>
      <webElementGuid>d3c5da9f-5a56-4a8f-9823-d6f213c6a96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost:8080/image/cache/catalog/demo/iphone_1-200x200.jpg' and @alt = 'iPhone' and @title = 'iPhone']</value>
      <webElementGuid>1ff09641-9b22-41b5-9ce3-5d6be7188c18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
